(define (make-monitored fun)
  (let ((count 0))
    (define (call param)
      (set! count (+ 1 count))
      (fun param))
    (define (dispatch param)
      (cond ((eq? param 'how-many-calls?) count)
	    (#t (call param))))
    dispatch))
